REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\mre_des_tools\mre_des_tools.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_des_tools\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_des_tools\include" -I "D:\MyGitHub\mre_des_tools\include\service" -I "D:\MyGitHub\mre_des_tools\include\component" -I "D:\MyGitHub\mre_des_tools\ResID" -I "D:\MyGitHub\mre_des_tools\src\app\widget" -I "D:\MyGitHub\mre_des_tools\src\app\launcher" -I "D:\MyGitHub\mre_des_tools\src\app\wallpaper" -I "D:\MyGitHub\mre_des_tools\src\app\screen_lock" -I "D:\MyGitHub\mre_des_tools\include\service" -I "D:\MyGitHub\mre_des_tools\include\component" -I "D:\MyGitHub\mre_des_tools\include\service" -I "D:\MyGitHub\mre_des_tools\src\framework" -I "D:\MyGitHub\mre_des_tools\src\framework\ui_core\base" -I "D:\MyGitHub\mre_des_tools\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_des_tools\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_des_tools\src\framework\mmi_core" -I "D:\MyGitHub\mre_des_tools\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_des_tools\src\component" -I "D:\MyGitHub\mre_des_tools\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_des_tools"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_des_tools\arm\mre_des_tools.o" -c "d:\MyGitHub\mre_des_tools\mre_des_tools.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_des_tools\include" -I "D:\MyGitHub\mre_des_tools\include\service" -I "D:\MyGitHub\mre_des_tools\include\component" -I "D:\MyGitHub\mre_des_tools\ResID" -I "D:\MyGitHub\mre_des_tools\src\app\widget" -I "D:\MyGitHub\mre_des_tools\src\app\launcher" -I "D:\MyGitHub\mre_des_tools\src\app\wallpaper" -I "D:\MyGitHub\mre_des_tools\src\app\screen_lock" -I "D:\MyGitHub\mre_des_tools\include\service" -I "D:\MyGitHub\mre_des_tools\include\component" -I "D:\MyGitHub\mre_des_tools\include\service" -I "D:\MyGitHub\mre_des_tools\src\framework" -I "D:\MyGitHub\mre_des_tools\src\framework\ui_core\base" -I "D:\MyGitHub\mre_des_tools\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_des_tools\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_des_tools\src\framework\mmi_core" -I "D:\MyGitHub\mre_des_tools\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_des_tools\src\component" -I "D:\MyGitHub\mre_des_tools\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_des_tools"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\mre_des_tools\mre_des_tools.axf"  "D:\MyGitHub\mre_des_tools\arm\gccmain.o"  "D:\MyGitHub\mre_des_tools\arm\mre_des_tools.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\pertcp.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persensor.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persmsper.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perbitstream.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\percontact.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\permms.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persmsmng.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\peraudio.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\percallout.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\percam.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perhttp.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persim.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perrecord.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persmssp.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perlbs.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perpro.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\pervideo.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perxml.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persec.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysstorage.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perpayment.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perbt.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perpn.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perudp.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persso.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\mre_des_tools\mre_des_tools.pkd" -e AXF "D:\MyGitHub\mre_des_tools\mre_des_tools.vcproj" "D:\MyGitHub\mre_des_tools\mre_des_tools.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\mre_des_tools\mre_des_tools.vcproj" "mre_des_tools" "0.1.0" "RDZDX" "1500" "NotSupportBg" "Not Support rotate" "mre_des_tools" "mre_des_tools" "mre_des_tools" "9123456789123456" "content" " TCP Sensor SMS(person) BitStream Contact MMS SMSMng Audio Call Camera File HTTP SIM card Record SMS(SP) LBS ProMng Video XML Sec SysStorage Payment BT PUSH UDP SysFile sso" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\mre_des_tools\arm D:\MyGitHub\mre_des_tools\build.log

